apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ipaddresspool.yaml
  - l2adv.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.15.2
    releaseName: metallb
    namespace: metallb-system
    valuesFile: values.yaml
