apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-cloudflare-api-token.sops.yaml
  - clusterissuer-letsencrypt-dns.yaml
  - clusterissuer-letsencrypt-http.yaml

generators:
  - ksops-secret-generator.yaml
